#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio 0.52
bspc config borderless_monocle = true
bspc config gapless_monocle = true
bspc config single_monocle = true &
bspc config pointer_motion_interval 5 &
bspc config border_width 0 &

#Autostart
bash ~/.config/polybar/launch.sh --shapes &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
sxhkd &
feh --bg-scale /home/kai/Downloads/wallpapers/nord-wallpaper.webp
sudo pacman -Syu pipewire pipewire-alsa pipewire-pulse pipewire-jack &
pactl set-sink-mute @DEFAULT_SINK@ 0
